<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="track_bot">

    <xacro:include filename="funtions.xacro"/>

<!-- ***** Body Setup ***** -->
    <xacro:property name="body_origin_x" value="0"/>
    <xacro:property name="body_origin_y" value="0"/>
    <xacro:property name="body_origin_z" value="0"/>

    <xacro:property name="body_size_x" value="2"/>
    <xacro:property name="body_size_y" value="1"/>
    <xacro:property name="body_size_z" value="0.5"/>

    <xacro:property name="body_mass" value="10"/>

    <xacro:macro name="body_origin">
        <origin xyz="${body_origin_x} ${body_origin_y} ${body_origin_z}" rpy="0 0 0"/>
    </xacro:macro>

    <xacro:macro name="body_shape">
        <geometry>
            <box size="${body_size_x} ${body_size_y} ${body_size_z}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="body_color">
        <material name="green"/>
    </xacro:macro>

    <xacro:macro name="body_link">
        <visual>
            <xacro:body_shape/>
            <xacro:body_color/>
        </visual>
        <collision>
            <xacro:body_shape/>
        </collision>
        <xacro:inertial_box mass="${body_mass}" x="${body_size_x}" y="${body_size_y}" z="${body_size_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </xacro:macro>
<!-- ***** Body Setup End ***** -->

<!-- ***** Wheel Setup ***** -->
    <xacro:property name="wheel_origin_x" value="0.8"/>
    <xacro:property name="wheel_origin_y" value="0.5"/>
    <xacro:property name="wheel_origin_z" value="-0.5"/>

    <xacro:property name="wheel_radius" value="0.25"/>
    <xacro:property name="wheel_length" value="0.5"/>

    <xacro:property name="wheel_mass" value="5"/>

    <xacro:macro name="wheel_offset_origin">
        <origin xyz="0 0 ${wheel_length/2}" rpy="0 0 0"/>
    </xacro:macro>

    <xacro:macro name="wheel_shape">
        <xacro:wheel_offset_origin/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="wheel_color">
        <material name="blue"/>
    </xacro:macro>

    <xacro:macro name="wheel_axis">
        <axis xyz="0 0 1"/>
    </xacro:macro>

    <xacro:macro name="wheel_link">
        <visual>
            <xacro:wheel_shape/>
            <xacro:wheel_color/>
        </visual>
        <collision>
            <xacro:wheel_shape/>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <xacro:wheel_offset_origin/>
        </xacro:inertial_cylinder>
    </xacro:macro>
<!-- ***** Wheel Setup End ***** -->

<!-- ***** Camera Setup ***** -->
    <xacro:property name="camera_origin_x" value="1"/>
    <xacro:property name="camera_origin_y" value="0"/>
    <xacro:property name="camera_origin_z" value="0.5"/>

    <xacro:property name="camera_size_x" value="0.1"/>
    <xacro:property name="camera_size_y" value="0.2"/>
    <xacro:property name="camera_size_z" value="0.2"/>

    <xacro:property name="camera_sensor_length" value="0.05"/>
    <xacro:property name="camera_sensor_radius" value="0.05"/>

    <xacro:property name="camera_mass" value="0.001"/>

    <xacro:macro name="camera_origin">
        <origin xyz="${camera_origin_x} ${camera_origin_y} ${camera_origin_z}" rpy="0 0 0"/>
    </xacro:macro>

    <xacro:macro name="camera_offset_origin">
        <origin xyz="${camera_size_x/2} 0 0" rpy="0 0 0"/>
    </xacro:macro>

    <xacro:macro name="camera_sensor_offset_origin">
        <origin xyz="${camera_sensor_length/2} 0 0" rpy="0 ${pi/2} 0"/>
    </xacro:macro>

    <xacro:macro name="camera_shape">
        <xacro:camera_offset_origin/>
        <geometry>
            <box size="${camera_size_x} ${camera_size_y} ${camera_size_z}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="camera_sensor_shape">
        <xacro:camera_sensor_offset_origin/>
        <geometry>
            <cylinder length="${camera_sensor_length}" radius="${camera_sensor_radius}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="camera_color">
        <material name="red"/>
    </xacro:macro>
<!-- ***** Camera Setup End***** -->

<!-- ***** Lidar Setup ***** -->
    <xacro:property name="lidar_origin_x" value="0"/>
    <xacro:property name="lidar_origin_y" value="0"/>
    <xacro:property name="lidar_origin_z" value="0.75"/>

    <xacro:property name="lidar_radius" value="0.1"/>
    <xacro:property name="lidar_length" value="0.1"/>

    <xacro:property name="lidar_sensor_radius" value="0.08"/>
    <xacro:property name="lidar_sensor_length" value="0.08"/>

    <xacro:property name="lidar_mass" value="0.001"/>

    <xacro:macro name="lidar_origin">
        <origin xyz="${lidar_origin_x} ${lidar_origin_y} ${lidar_origin_z}" rpy="0 0 0"/>
    </xacro:macro>

    <xacro:macro name="lidar_offset_origin">
        <origin xyz="0 0 ${lidar_length/2}" rpy="0 0 0"/>
    </xacro:macro>

    <xacro:macro name="lidar_sensor_offset_origin">
        <origin xyz="0 0 ${lidar_sensor_length/2}" rpy="0 0 0"/>
    </xacro:macro>

    <xacro:macro name="lidar_shape">
        <xacro:lidar_offset_origin/>
        <geometry>
            <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="lidar_sensor_shape">
        <xacro:lidar_sensor_offset_origin/>
        <geometry>
            <cylinder length="${lidar_sensor_length}" radius="${lidar_sensor_radius}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="lidar_color">
        <material name="red"/>
    </xacro:macro>
<!-- ***** Lidar Setup End ***** -->

    <link name="base_link"></link>

<!-- ***** Body Parts ***** -->
    <joint name="body_joint" type="fixed">
        <xacro:body_origin/>
        <parent link="base_link"/>
        <child link="body_link"/>        
    </joint>

    <link name="body_link">
        <xacro:body_link/>
    </link>
<!-- ***** Body Parts End ***** -->

<!-- ***** Wheel Parts ***** -->
    <joint name="FR_wheel_joint" type="continuous">
        <parent link="body_link"/>
        <child link="FR_wheel_link"/>
        <origin xyz="${wheel_origin_x} -${wheel_origin_y} ${wheel_origin_z}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="FR_wheel_link">
        <xacro:wheel_link/>
    </link>

    <joint name="FL_wheel_joint" type="continuous">
        <parent link="body_link"/>
        <child link="FL_wheel_link"/>
        <origin xyz="${wheel_origin_x} ${wheel_origin_y} ${wheel_origin_z}" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="FL_wheel_link">
        <xacro:wheel_link/>
    </link>

    <joint name="RR_wheel_joint" type="continuous">
        <parent link="body_link"/>
        <child link="RR_wheel_link"/>
        <origin xyz="-${wheel_origin_x} -${wheel_origin_y} ${wheel_origin_z}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="RR_wheel_link">
        <xacro:wheel_link/>
    </link>

    <joint name="RL_wheel_joint" type="continuous">
        <parent link="body_link"/>
        <child link="RL_wheel_link"/>
        <origin xyz="-${wheel_origin_x} ${wheel_origin_y} ${wheel_origin_z}" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="RL_wheel_link">
        <xacro:wheel_link/>
    </link>
<!-- ***** Wheel Parts End ***** -->

<!-- ***** Camera Parts ***** -->
    <joint name="camera_joint" type="fixed">
        <xacro:camera_origin/>
        <parent link="body_link"/>
        <child link="camera_link"/>        
    </joint>

    <link name="camera_link">
        <visual>
            <xacro:camera_shape/>
            <xacro:camera_color/>
        </visual>

        <collision>
            <xacro:camera_shape/>
        </collision>

        <xacro:inertial_box mass="${camera_mass}" x="${camera_size_x}" y="${camera_size_y}" z="${camera_size_z}">
            <xacro:camera_offset_origin/>
        </xacro:inertial_box>
    </link>

    <joint name="camera_sensor_joint" type="fixed">
        <origin xyz="${camera_size_x} 0 0" rpy="0 0 0"/>
        <parent link="camera_link"/>
        <child link="camera_sensor_link"/>
    </joint>

    <link name="camera_sensor_link">
        <visual>
            <xacro:camera_sensor_shape/>
            <xacro:camera_color/>
        </visual>
        <collision>
            <xacro:camera_sensor_shape/>
        </collision>
        <xacro:inertial_cylinder mass="${camera_mass}" length="${camera_sensor_length}" radius="${camera_sensor_radius}">
            <xacro:camera_sensor_offset_origin/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${pi/2} 0 -${pi/2}"/>
        <parent link="camera_sensor_link"/>
        <child link="camera_optical_link"/>
    </joint>

    <link name="camera_optical_link"></link>
<!-- ***** Camera Parts End ***** -->

<!-- ***** Lidar Parts ***** -->
    <joint name="lidar_joint" type="fixed">
        <xacro:lidar_origin/>
        <parent link="body_link"/>
        <child link="lidar_link"/>
    </joint>

    <link name="lidar_link">
        <visual>
            <xacro:lidar_shape/>
            <xacro:lidar_color/>
        </visual>
        <collision>
            <xacro:lidar_shape/>
        </collision>
        <xacro:inertial_cylinder mass="${lidar_mass}" length="${lidar_length}" radius="${lidar_radius}">
            <xacro:lidar_offset_origin/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="lidar_sensor_joint" type="fixed">
        <origin xyz="0 0 ${lidar_length}" rpy="0 0 0"/>
        <parent link="lidar_link"/>
        <child link="lidar_sensor_link"/>
    </joint>

    <link name="lidar_sensor_link">
        <visual>
            <xacro:lidar_sensor_shape/>
            <xacro:lidar_color/>
        </visual>
        <collision>
            <xacro:lidar_sensor_shape/>
        </collision>
        <xacro:inertial_cylinder mass="${lidar_mass}" length="${lidar_sensor_length}" radius="${lidar_sensor_radius}">
            <xacro:lidar_sensor_offset_origin/>
        </xacro:inertial_cylinder>
    </link>
<!-- ***** Lidar Parts End ***** -->

<!-- ***** Ultrasoni Sensor Parts ***** -->
    <joint name="ultrasonic_joint" type="fixed">
        <origin xyz="1.5 0 0" rpy="0 0 0"/>
        <parent link="body_link"/>
        <child link="ultrasonic_link"/>        
    </joint>

    <link name="ultrasonic_link">
        <visual>
            <geometry>
                <box size="0.05 0.2 0.1"/>
            </geometry>
        </visual>
    </link>
<!-- ***** Ultrasoni Sensor Parts End ***** -->

    <xacro:include filename="gazebo.xacro"/>

</robot>